name: Repository Dispatch Listener

on:
  repository_dispatch:
    types: [run-tests, deploy]

jobs:
  print-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Print payload
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Payload env: ${{ github.event.client_payload.env }}"
          echo "Payload version: ${{ github.event.client_payload.version }}"
          echo "Payload region: ${{ github.event.client_payload.region }}"

      - name: Print payload
        run: echo "${{ github.event.client_payload }}"
